apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        command:
        - /bin/bash
        - -cex
        - |
          exec nginx -g 'daemon off;'
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      - name: metrics
        image: "bitnami/nginx-exporter:0.10.0-debian-10-r150"
        imagePullPolicy: IfNotPresent
        command: ['/usr/bin/exporter', '-nginx.scrape-uri', 'http://127.0.0.1/status']
        ports:
          - name: metrics
            containerPort: 9113
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          defaultMode: 0555
